package main

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"testing"

	"github.com/alecthomas/kong"
)

// README's command list is generated from the Kong grammar, not hand-kept
// (ferret-din). A hand-written list documented 10 of 41 commands and asserted a
// flag contract ("everything takes --data/--format/--limit/--max-bytes") that
// only the corpus commands honor. The fix is to stop writing the list by hand:
// this test regenerates it from the same grammar the binary parses and fails
// when the two disagree, so adding a command without documenting it is a red
// build rather than a silent drift.
const (
	readmePath      = "../../README.md"
	commandsBegin   = "<!-- BEGIN COMMANDS (generated by cmd/ferret/readme_test.go) -->"
	commandsEnd     = "<!-- END COMMANDS -->"
	updateReadmeEnv = "FERRET_UPDATE_README"
)

// commonFlagNames are the four flags README used to claim every command takes.
// They come from CommonFlags; a command has them only if it embeds that struct.
var commonFlagNames = []string{"data", "format", "limit", "max-bytes"}

type cmdRow struct {
	path  string   // "burn", "fixes sub"
	help  string   // one-line help from the kong tag
	flags []string // this command's own flags, in declaration order
}

// surfaceCell renders a command's commandSurfaces entry (surface.go) for the
// README table. It reads the classification struct directly, not the
// labelled help text labelCommandHelp stamps into --help — the two must not
// be conflated, or README's help strings stop being clean prose and start
// carrying a formatting dependency on the map.
func surfaceCell(path string) string {
	s, ok := commandSurfaces[path]
	if !ok {
		// Unreached in a green build: TestCommandSurfacesExhaustive
		// (surface_test.go) fails first if a command has no entry.
		return "?"
	}
	if s.escalates != "" {
		return fmt.Sprintf("local, model with `%s`", s.escalates)
	}
	return string(s.kind)
}

// commandRows walks the parsed Kong grammar and returns one row per runnable
// command (leaf nodes), depth-first in declaration order. Groups that only hold
// subcommands ("fixes", "feedback") contribute their prefix, not a row.
func commandRows(t *testing.T) []cmdRow {
	t.Helper()
	k, err := kong.New(&CLI, kong.Name("ferret"))
	if err != nil {
		t.Fatalf("kong.New: %v", err)
	}

	var rows []cmdRow
	var walk func(n *kong.Node, prefix string)
	walk = func(n *kong.Node, prefix string) {
		for _, c := range n.Children {
			path := strings.TrimSpace(prefix + " " + c.Name)
			if len(c.Children) > 0 {
				walk(c, path)
				continue
			}
			names := make([]string, 0, len(c.Flags))
			for _, f := range c.Flags {
				names = append(names, f.Name)
			}
			rows = append(rows, cmdRow{path: path, help: collapseSpace(c.Help), flags: names})
		}
	}
	walk(k.Model.Node, "")
	return rows
}

func collapseSpace(s string) string { return strings.Join(strings.Fields(s), " ") }

// hasCommonFlags reports whether a command embeds CommonFlags — i.e. whether
// the --data/--format/--limit/--max-bytes contract actually holds for it.
func hasCommonFlags(flags []string) bool {
	have := make(map[string]bool, len(flags))
	for _, f := range flags {
		have[f] = true
	}
	for _, want := range commonFlagNames {
		if !have[want] {
			return false
		}
	}
	return true
}

// ownFlags returns a command's flags minus the common four, so the rendered
// table shows what is specific to that command.
func ownFlags(flags []string) []string {
	common := make(map[string]bool, len(commonFlagNames))
	for _, f := range commonFlagNames {
		common[f] = true
	}
	var own []string
	for _, f := range flags {
		if !common[f] {
			own = append(own, f)
		}
	}
	return own
}

// renderCommands emits the generated README block: one table row per command,
// naming whether it takes the common flag set and what else it accepts.
func renderCommands(rows []cmdRow) string {
	var b strings.Builder
	b.WriteString(commandsBegin)
	b.WriteString("\n\n")
	fmt.Fprintf(&b, "%d commands. **Surface** = `local` (reads the corpus/transcripts, nothing leaves the machine), `model` (sends transcript-derived material to the Anthropic API — costs money; refused under `--offline`/`FERRET_OFFLINE=1`), or `hook` (invoked by a Claude Code hook, not typed by hand). **Common flags** = `--data DIR` (default `~/.ferret`), `--format`, `--limit`, `--max-bytes`; only the corpus commands take them, and the rest are listed per row. Truncation is never silent.\n\n", len(rows))
	b.WriteString("| Command | Surface | Common flags | Other flags | What it does |\n")
	b.WriteString("|---|---|---|---|---|\n")
	for _, r := range rows {
		common := "—"
		own := r.flags
		if hasCommonFlags(r.flags) {
			common = "✓"
			own = ownFlags(r.flags)
		}
		otherCell := "—"
		if len(own) > 0 {
			quoted := make([]string, 0, len(own))
			for _, f := range own {
				quoted = append(quoted, "`--"+f+"`")
			}
			otherCell = strings.Join(quoted, " ")
		}
		fmt.Fprintf(&b, "| `ferret %s` | %s | %s | %s | %s |\n", r.path, surfaceCell(r.path), common, otherCell, escapePipes(r.help))
	}
	b.WriteString("\n")
	b.WriteString(commandsEnd)
	return b.String()
}

func escapePipes(s string) string { return strings.ReplaceAll(s, "|", `\|`) }

// TestREADMECommandsGenerated is the snapshot gate: README's command table must
// equal what the current grammar renders. Regenerate with
// FERRET_UPDATE_README=1 go test ./cmd/ferret -run TestREADMECommandsGenerated
func TestREADMECommandsGenerated(t *testing.T) {
	raw, err := os.ReadFile(readmePath)
	if err != nil {
		t.Fatalf("read README: %v", err)
	}
	readme := string(raw)

	want := renderCommands(commandRows(t))

	start := strings.Index(readme, commandsBegin)
	end := strings.Index(readme, commandsEnd)
	if start < 0 || end < 0 || end < start {
		t.Fatalf("README is missing the generated command block markers %q / %q", commandsBegin, commandsEnd)
	}
	got := readme[start : end+len(commandsEnd)]
	if got == want {
		return
	}

	if os.Getenv(updateReadmeEnv) == "1" {
		updated := readme[:start] + want + readme[end+len(commandsEnd):]
		if err := os.WriteFile(readmePath, []byte(updated), 0o600); err != nil {
			t.Fatalf("write README: %v", err)
		}
		t.Logf("README command block regenerated (%d commands)", len(commandRows(t)))
		return
	}

	t.Errorf("README command table is stale — a command's name, flags or help changed.\n"+
		"Regenerate:\n  %s=1 go test ./cmd/ferret -run TestREADMECommandsGenerated\n\n%s",
		updateReadmeEnv, firstDiff(got, want))
}

// firstDiff reports the first differing line, which is enough to see what
// changed without dumping a 40-row table into the failure output.
func firstDiff(got, want string) string {
	g, w := strings.Split(got, "\n"), strings.Split(want, "\n")
	for i := 0; i < len(g) || i < len(w); i++ {
		gl, wl := "", ""
		if i < len(g) {
			gl = g[i]
		}
		if i < len(w) {
			wl = w[i]
		}
		if gl != wl {
			return fmt.Sprintf("first difference at line %d:\n  README:    %s\n  generated: %s", i+1, gl, wl)
		}
	}
	return "(no line differs — trailing whitespace?)"
}

// TestREADMEFlagContractHolds is the claim README:27 used to get wrong: it
// asserted the common four applied to every command. Pin the true partition so
// a future edit cannot restore the false blanket claim unnoticed.
func TestREADMEFlagContractHolds(t *testing.T) {
	rows := commandRows(t)
	if len(rows) == 0 {
		t.Fatal("no commands found in the grammar")
	}

	var withCommon, withoutCommon []string
	for _, r := range rows {
		if hasCommonFlags(r.flags) {
			withCommon = append(withCommon, r.path)
			continue
		}
		withoutCommon = append(withoutCommon, r.path)
	}
	sort.Strings(withoutCommon)

	if len(withoutCommon) == 0 {
		t.Fatal("every command now takes the common flags — README's per-row table should be simplified back to a blanket claim")
	}
	if len(withCommon) == 0 {
		t.Fatal("no command takes the common flags — CommonFlags is no longer embedded anywhere")
	}
	t.Logf("%d commands take the common flags, %d do not: %s",
		len(withCommon), len(withoutCommon), strings.Join(withoutCommon, ", "))
}
